[package]
name = "qb-downloader-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
log = "0.4"
md5 = "0.7"
reqwest = {version = "0.12", features = ["cookies", "json", "stream", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
directories-next = "2.0.0"
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync"] }
futures = "0.3.31"
