name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
env:
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        toolchain:
          - stable
        platform:
          - os-name: Linux-x86_64-musl
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64-musl
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-x86_64-gnu
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install musl tools for musl targets
        if: contains(matrix.platform.target, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build frontend
        working-directory: ui
        run: |
          npm install
          npm run build
    
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: qb-downloader
          target: ${{ matrix.platform.target }}